### ISSUE TITLE
[Bug] Rematerialization failed with CNN models

### ISSUE THREAD

**Issue by comaniac** [awslabs/raf#8]
Looks like there's a bug in rematerialization pass when handling in-place update with tuple (maybe due to batch norm?)
Note that FP32 models work well but only AMP models have this issue.

```
[2022-04-11 09:02:23]    INFO Util: Initialize model bencher...2.24s
[2022-04-11 09:04:23]    INFO Util: Initialize model bencher...122.06s
[2022-04-11 09:04:31]    INFO RAF: AMP enabled in RAF.
[2022-04-11 09:04:32]    INFO RAF: Rematerialization enabled in RAF
[09:04:41] /__w/models/models/raf_workspace/raf/src/pass/rematerialization.cc:992: Using profiler-based cost estimation for rematerialization. This may take a while. 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/__w/models/models/raf_workspace/benchmark/__main__.py", line 246, in <module>
    main()
  File "/__w/models/models/raf_workspace/benchmark/__main__.py", line 154, in main
    ltc=args.ltc,
  File "/__w/models/models/raf_workspace/benchmark/model_bencher.py", line 68, in bench
    t_setup(device, **kwargs)
  File "/__w/models/models/raf_workspace/benchmark/raf/raf_bencher.py", line 326, in bench_train_setup
    remat,
  File "/__w/models/models/raf_workspace/benchmark/raf/raf_bencher.py", line 158, in get_vm_exec
    self.vm = VMExecutor(mod, device, dryrun=dryrun)
  File "/usr/local/lib/python3.6/dist-packages/raf/_core/executor.py", line 130, in __init__
    self.executable = vm.compile(mod, self.device)
  File "/usr/local/lib/python3.6/dist-packages/raf/_core/vm.py", line 397, in compile
    compiler.lower(mod, device)
  File "/usr/local/lib/python3.6/dist-packages/raf/_core/vm.py", line 296, in lower
    self._lower(mod, device)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 323, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 257, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 246, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 163, in tvm._ffi._cy3.core.CALL
tvm._ffi.base.TVMError: Traceback (most recent call last):
  14: TVMFuncCall
  13: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<raf::executor::vm::VMCompiler::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  12: raf::executor::vm::VMCompiler::Lower(tvm::IRModule, tvm::runtime::Map<tvm::Integer, raf::Device, void, void> const&)
  11: raf::executor::vm::VMCompiler::OptimizeModule(tvm::IRModule const&, tvm::runtime::Map<tvm::Integer, raf::Device, void, void> const&)
  10: tvm::transform::Pass::operator()(tvm::IRModule) const
  9: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  8: raf::pass::RAFSequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  7: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  6: raf::pass::RAFSequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  5: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  4: raf::pass::RAFFunctionPassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  3: _ZN3tvm7runtime13PackedFuncObj9ExtractorINS0_16PackedFuncSubObjIZNS0_15TypedPackedFuncIFNS_5relay8FunctionES6_NS_8IRModuleENS_9transform11PassContextEEE17AssignTypedLambdaIZN3raf4pass17RematerializationEvEUlS6_S7_S9_E_EEvT_EUlRKNS0_7TVMArgsEPNS0_11TVMRetValueEE_EEE4CallEPKS1_SH_SL_
  2: raf::pass::Rematerialization()::{lambda(tvm::relay::Function, tvm::IRModule, tvm::transform::PassContext)#1}::operator()(tvm::relay::Function, tvm::IRModule, tvm::transform::PassContext) const [clone .isra.705]
  1: raf::pass::rematerialization::Rematerializer::AnalyzeTensors(raf::Device const&, tvm::relay::Function const&, tvm::IRModule const&, raf::pass::liveness_analysis::LivenessAnalyzer*, raf::op_profiler::OpProfiler*)
  0: raf::pass::rematerialization::Rematerializer::TensorAnalyzer::Run()
  File "/__w/models/models/raf_workspace/raf/src/pass/rematerialization.cc", line 894
TVMError: Check failed: cand_liveness_vars.size() == 1U (107 vs. 1) : 
```

Reproduce using benchmark:

```
python3 -m benchmark bench --framework raf --model resnet50 --batch 16 --amp
```

cc @zhouyuan1119

**Comment by zhouyuan1119** [comment]
This check failure is triggered because of nested tuples at the end of the function:
```
  ...
  let %x1259 = (%x367, ...);
  %x1259
}
```
where `x367` is also a tuple:
```
let %x367 = (%x260, %x261, ...);
...
```
Will send a fix later this week.
